services:
  web:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-${UID:-1000}}
    volumes:
      - ./log:/rails/log
      - ./storage:/rails/storage
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://e_commerce:e_commerce_password@postgres-db/e_commerce_development
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
    secrets:
      - source: master_key
        target: /rails/config/master.key
    depends_on:
      postgres-db:
        condition: service_healthy

  postgres-db:
    image: postgres
    environment:
      POSTGRES_USER: e_commerce
      POSTGRES_PASSWORD: e_commerce_password
    volumes:
      - ./tmp/postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d e_commerce_development -U e_commerce"]
      interval: 2s
      timeout: 5s
      retries: 30

secrets:
  master_key:
    file: ./config/master.key
