databases:
  - name: e-commerce
    databaseName: e_commerce_production
    user: ecommerce
    plan: free

services:
  - type: web
    name: e-commerce
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: e-commerce
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: WEB_CONCURRENCY
        value: 2
